################################
######                     #####
######       环境配置       #####
######                     #####
################################


# 服务器配置
server:
  port: 8062
  servlet:
    path: /front/





# 引入base中的配置文件
spring:
  profiles:
    include: base