################################
######                     #####
######     主配置文件       #####
######                     #####
################################

# 此配置文件是为了单元测试时使用

# 引入配置文件
spring:
  profiles:
    active: base

