################################
######                     #####
######       环境配置       #####
######                     #####
################################


# 服务器配置
server:
  port: 8061
  servlet:
    path: /manager/





# 引入base中的配置文件
spring:
    profiles:
        include: base

